# Generated by Django 3.0.5 on 2020-04-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='ActiveCases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='NewCases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='NewDeaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='RationPerMillion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='TotalCases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='TotalDeaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='TotalRecovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='bnName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='country',
            name='iso3',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='country',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='SeriousCases',
            field=models.IntegerField(default=0),
        ),
    ]
